site_name: RL4CO
site_url: https://ai4co.github.io/rl4co/
repo_name: ai4co/rl4co
repo_url: https://github.com/ai4co/rl4co/
edit_uri: edit/main/docs
site_description: Official documentation for RL4CO
copyright: Made with ❤️ by AI4CO contributors
docs_dir: .

nav:
  - Home: README.md
  - Getting Started:
    - Installation: docs/content/start/installation.md
    - Quick Start: docs/content/examples/1-quickstart.ipynb
    - Training with Hydra: docs/content/start/hydra.md
    - NCO Methods: docs/content/api/models/common/__init__
  - Tutorials:
    - Training a Model: examples/2-full-training.ipynb
    - New Environment: examples/3-creating-new-env-model.ipynb
    - Decoding Strategies: examples/modeling/1-decoding-strategies.ipynb
    - Transductive Methods: examples/modeling/2-transductive-methods.ipynb
    - Encoder Customization: examples/modeling/3-change-encoder.ipynb
    - Hydra Configuration: examples/advanced/1-hydra-config.ipynb
  - RL Algorithms:
    - Base Algorithms: docs/content/api/algos/base.md
    - Reinforce: docs/content/api/algos/reinforce.md
    - PPO: docs/content/api/algos/ppo.md
    - A2C: docs/content/api/algos/a2c.md
  - Environments:
    - Basic Environments: docs/content/api/envs/base.md
    - EDA Problems: docs/content/api/envs/eda.md
    - Routing Problems: docs/content/api/envs/routing.md
    - Scheduling Problems: docs/content/api/envs/scheduling.md
  - Networks:
    - Neural Network Modules: docs/content/api/models/nn.md
    - Environment Embeddings: docs/content/api/models/env_embeddings.md
  - Base NCO Methods:
    - Constructive Policies: docs/content/api/models/common/zoo/constructive.md
    - Improvement Policies: docs/content/api/models/common/zoo/improvement.md
    - Transductive Models: docs/content/api/models/common/zoo/transductive.md
  - Additional APIs:
    - Train and Evaluation: docs/content/api/tasks.md
    - Decoding Strategies: docs/content/api/decoding.md
    - Data: docs/content/api/data.md
  - Other:
    - Contributing to RL4CO: docs/content/general/contribute.md
    - FAQ: docs/content/general/faq.md

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/ai4co
  - icon: fontawesome/brands/slack
    link: https://bit.ly/ai4co-slack
  - icon: fontawesome/solid/globe
    link: https://ai4co.org

theme:
  name: material
  logo: docs/assets/figs/rl4co-logo.svg
  favicon: docs/assets/figs/rl4co-logo.svg
  primary: red
  features:
    - announce.dismiss
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.tabs # horizontal tabs for navigation
    - navigation.tabs.sticky # tabs do not scroll out of view
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  font:
    text: Noto Sans
    code: Fira Code

extra_css:
  - docs/stylesheets/extra.css # Our custom CSS
  - docs/stylesheets/mkdocstrings.css # mkdocstrings CSS
  - https://unpkg.com/katex@0/dist/katex.min.css # Latex math rendering

extra_javascript:
  - js/katex.js # Latex math rendering
  - https://unpkg.com/katex@0/dist/katex.min.js # Latex math rendering
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js # Latex math rendering

extra:
  version:
    default: stable

plugins:
  - mkdocstrings:
      enable_inventory: true # create .inv file for auto linking
      handlers:
        python:
          paths: [rl4co]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            docstring_section_style: list
            heading_level: 1
            inherited_members: false
            show_root_heading: true
            show_root_full_path: false
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            extensions:
            - griffe_inherited_docstrings
          import:
            - https://docs.python.org/3/objects.inv
            - https://pytorch.org/rl/stable/objects.inv
            - https://pytorch.org/tensordict/stable/objects.inv
            - https://pytorch.org/docs/stable/objects.inv
            - https://lightning.ai/docs/pytorch/stable/objects.inv
  - mike:
      alias_type: symlink
      canonical_version: latest
  # - mkdocs-jupyter:
  #     include_source: True
  - search
  - autorefs
  - autolinks
  - same-dir 

hooks:
  - docs/hooks.py

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - def_list
  - mdx_truly_sane_lists
  - mdx_breakless_lists
  - gfm_admonition

