_target_: "src.tasks.dynamics.DynamicsTask"

# Task is the LightningModule that is trained. 
# We divide call this task to differentiate and the Model (nn.Module)
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
  weight_decay: 1e-5
# loss_fn:
#   _target_: torch.nn.MSELoss
# clamp_output: [0, null] # null is None in Python