_target_: rl4co.envs.MDCPDPEnv
name: mdcpdp

num_loc: 20
num_depot: 4
min_loc: 0
max_loc: 1
min_capacity: 1
max_capacity: 2
depot_mode: multiple

data_dir: ${paths.root_dir}/data/mdcpdp
val_file: mdcpdp${env.num_loc}_val_seed4321.npz
test_file: mdcpdp${env.num_loc}_test_seed1234.npz